import {
  Injectable,
  NotFoundException,
  ForbiddenException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { Request } from './entities/request.entity';
import { SavedRequest } from './entities/saved-request.entity';
import { AccessLog, AccessAction } from './entities/access-log.entity';
import { Task } from '@modules/tasks/entities/task.entity';
import { User } from '@modules/users/entities/user.entity';
import {
  RequestStatus,
  ClearanceLevel,
  SystemRole,
  AssignmentStatus,
  TaskOrigin,
  TaskStatus,
  RequestCategory,
} from '@common/enums';
import { CreateRequestDto, AddInfoRequestDto } from './dto/create-request.dto';
import { UpdateRequestDto } from './dto/update-request.dto';
import { FindRequestsDto } from './dto/find-requests.dto';

/** Радіус обфускування координат у метрах (з env або 3 км за замовчуванням) */
const OBFUSCATION_RADIUS_M = parseInt(
  process.env.LOCATION_OBFUSCATION_RADIUS_M || '3000',
  10,
);

const CATEGORY_KEYWORDS: Record<string, string[]> = {
  '#Медицина': ['медик', 'лікар', 'аптека', 'ліки', 'перев\'язка', 'медична'],
  '#Евакуація': ['евакуація', 'евакуювати', 'вивезти', 'виїхати', 'перевезти'],
  '#Термінова': ['терміново', 'критично', 'негайно'],
  '#Продовольство': ['їжа', 'продукти', 'харчування', 'вода'],
  '#Логістика': ['доставка', 'перевезення', 'транспорт'],
  '#Військо': ['армія', 'зсу', 'підрозділ', 'бойовий', 'фронт'],
};

/** Мапа категорії -> автотег, яка додається при створенні/оновленні заявки */
const CATEGORY_TO_TAG: Record<RequestCategory, string | null> = {
  [RequestCategory.MEDICAL]: '#Медицина',
  [RequestCategory.EVACUATION]: '#Евакуація',
  [RequestCategory.LOGISTICS]: '#Логістика',
  [RequestCategory.MILITARY]: '#Військо',
  [RequestCategory.HUMANITARIAN]: '#Гуманітарна',
  [RequestCategory.SHELTER]: '#Житло',
  [RequestCategory.PSYCHOLOGICAL]: '#Психологічна',
  [RequestCategory.OTHER]: null,
};

const isActiveAssignmentStatus = (status: AssignmentStatus | string): boolean =>
  status !== AssignmentStatus.WITHDRAWN && status !== AssignmentStatus.COMPLETED;

@Injectable()
export class RequestsService {
  constructor(
    @InjectRepository(Request)
    private readonly requestRepository: Repository<Request>,
    @InjectRepository(SavedRequest)
    private readonly savedRequestRepository: Repository<SavedRequest>,
    @InjectRepository(AccessLog)
    private readonly accessLogRepository: Repository<AccessLog>,
    @InjectRepository(Task)
    private readonly taskRepository: Repository<Task>,
  ) {}

  // ─── Створення заявки ─────────────────────────────────────────────────────

  async create(dto: CreateRequestDto, creator: User): Promise<Request> {
    const textTags = this.autoCategorizeTags(dto.title + ' ' + (dto.description || ''));
    const categoryTag = dto.category ? CATEGORY_TO_TAG[dto.category] : null;
    const tags = [...new Set([...textTags, ...(categoryTag ? [categoryTag] : [])])];

    const request = this.requestRepository.create({
      ...dto,
      creatorId: creator.id,
      tags,
    });

    const saved = await this.requestRepository.save(request);

    await this.taskRepository.save(
      this.taskRepository.create({
        requestId: saved.id,
        title: 'Виконати заявку',
        description: dto.description || null,
        neededPeopleCount: 1,
        requiredRoles: [],
        priority: 0,
        deadline: dto.deadline ? new Date(dto.deadline) : null,
        status: TaskStatus.TODO,
        origin: TaskOrigin.SYSTEM,
        createdByUserId: creator.id,
        isAutoGenerated: true,
      }),
    );

    if (dto.latitude != null && dto.longitude != null) {
      await this.requestRepository.query(
        `UPDATE requests
         SET exact_location = ST_SetSRID(ST_MakePoint($1, $2), 4326)
         WHERE id = $3`,
        [dto.longitude, dto.latitude, saved.id],
      );
    }

    return saved;
  }

  // ─── Список заявок ────────────────────────────────────────────────────────

  async findAll(dto: FindRequestsDto, requester: User): Promise<(Request & { isSaved?: boolean })[]> {
    const qb = this.requestRepository
      .createQueryBuilder('request')
      .leftJoinAndSelect('request.creator', 'creator')
      .leftJoinAndSelect('request.tasks', 'tasks')
      .where('request.deleted_at IS NULL');

    if (dto.status)    qb.andWhere('request.status = :status',     { status: dto.status });
    if (dto.category)  qb.andWhere('request.category = :category', { category: dto.category });
    if (dto.urgency)   qb.andWhere('request.urgency = :urgency',   { urgency: dto.urgency });
    if (dto.creatorId) qb.andWhere('request.creatorId = :creatorId', { creatorId: dto.creatorId });
    if (dto.excludeCreatorId) {
      qb.andWhere('request.creatorId != :excludeCreatorId', { excludeCreatorId: dto.excludeCreatorId });
    }

    if (dto.search) {
      qb.andWhere(
        '(request.title ILIKE :search OR request.description ILIKE :search)',
        { search: `%${dto.search}%` },
      );
    }

    const userClearanceRank = this.getClearanceRank(requester.clearanceLevel);
    if (requester.systemRole !== SystemRole.ADMIN) {
      qb.andWhere(
        `CASE request.required_clearance
          WHEN 'local' THEN 0
          WHEN 'international' THEN 1
          WHEN 'frontline' THEN 2
         END <= :userRank`,
        { userRank: userClearanceRank },
      );
    }

    if (dto.latitude != null && dto.longitude != null && dto.radiusKm) {
      const radiusM = dto.radiusKm * 1000;
      qb.andWhere(
        `request.exact_location IS NOT NULL AND
         ST_DWithin(
           request.exact_location::geography,
           ST_SetSRID(ST_MakePoint(:lng, :lat), 4326)::geography,
           :radius
         )`,
        { lat: dto.latitude, lng: dto.longitude, radius: radiusM },
      );
      qb.orderBy(
        `ST_Distance(
          request.exact_location::geography,
          ST_SetSRID(ST_MakePoint(:lng, :lat), 4326)::geography
        )`,
        'ASC',
      );
    } else {
      qb.orderBy('request.created_at', 'DESC');
    }

    qb.limit(dto.limit || 50).offset(dto.offset || 0);

    const requests = await qb.getMany();

    const savedRequestIds = new Set(
      (await this.savedRequestRepository.find({
        where: { userId: requester.id },
        select: ['requestId'],
      })).map(s => s.requestId)
    );

    return requests.map((r) => {
      const obfuscated = this.obfuscateLocation(r, requester);
      return { ...obfuscated, isSaved: savedRequestIds.has(r.id), taskCount: r.tasks?.length ?? 0 };
    });
  }

  // ─── Деталі заявки ────────────────────────────────────────────────────────

  async findOne(id: string, requester: User): Promise<Request & { isSaved?: boolean }> {
    const request = await this.requestRepository
      .createQueryBuilder('request')
      .leftJoinAndSelect('request.creator', 'creator')
      .leftJoinAndSelect('request.tasks', 'tasks')
      .leftJoinAndSelect('tasks.assignments', 'assignments')
      .leftJoinAndSelect('assignments.user', 'assignmentUser')
      .where('request.id = :id', { id })
      .getOne();

    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    this.checkClearanceAccess(request, requester);

    const obfuscated = this.obfuscateLocation(request, requester);

    const isSaved = await this.savedRequestRepository.exists({
      where: { requestId: id, userId: requester.id }
    });

    // Логування доступу для FRONTLINE заявок (крім власника)
    this.logAccess(request, requester, 'view_detail');

    return {
      ...obfuscated,
      isSaved,
    };
  }

  // ─── Оновлення ────────────────────────────────────────────────────────────

  async update(id: string, dto: UpdateRequestDto, requester: User): Promise<Request> {
    const request = await this.requestRepository.findOne({
      where: { id },
      relations: ['tasks', 'tasks.assignments'],
    });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== requester.id && requester.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Немає прав для редагування цієї заявки');
    }

    const hasActiveAssignments = request.tasks?.some((task) =>
      task.assignments?.some((a) => isActiveAssignmentStatus(a.status)),
    );

    if (hasActiveAssignments && requester.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException(
        'Не можна редагувати заявку, яку вже взяли в роботу волонтери.',
      );
    }

    if (dto.mediaUrls) {
      const existing = request.mediaUrls || [];
      const newUrls = ((dto as any).mediaUrls as typeof request.mediaUrls) || [];
      request.mediaUrls = [...existing, ...newUrls];
    }

    Object.assign(request, { ...dto, mediaUrls: request.mediaUrls });

    if (dto.title || dto.description || dto.category) {
      const textTags = this.autoCategorizeTags(
        (dto.title || request.title) + ' ' + (dto.description || request.description || ''),
      );
      const effectiveCategory = dto.category || request.category;
      const categoryTag = effectiveCategory ? CATEGORY_TO_TAG[effectiveCategory] : null;
      request.tags = [...new Set([...textTags, ...(categoryTag ? [categoryTag] : [])])];
    }

    const saved = await this.requestRepository.save(request);

    const lat = (dto as any).latitude ?? request.latitude;
    const lng = (dto as any).longitude ?? request.longitude;
    if (lat != null && lng != null) {
      await this.requestRepository.query(
        `UPDATE requests SET exact_location = ST_SetSRID(ST_MakePoint($1, $2), 4326) WHERE id = $3`,
        [lng, lat, id],
      );
    }

    return saved;
  }

  async addInfo(id: string, dto: AddInfoRequestDto, requester: User): Promise<Request> {
    const request = await this.requestRepository.findOne({ where: { id } });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== requester.id && requester.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Тільки власник або адміністратор може доповнювати інформацію');
    }

    if (!request.additionalInfo) request.additionalInfo = [];
    request.additionalInfo.push({
      id: uuidv4(),
      text: dto.text,
      attachments: dto.attachments || [],
      createdAt: new Date(),
    });

    return await this.requestRepository.save(request);
  }

  async updateAdditionalInfo(
    id: string,
    infoId: string,
    dto: AddInfoRequestDto,
    requester: User,
  ): Promise<Request> {
    const request = await this.requestRepository.findOne({ where: { id } });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== requester.id && requester.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Тільки власник або адміністратор може редагувати доповнення');
    }

    const infoIndex = request.additionalInfo.findIndex((info) => info.id === infoId);
    if (infoIndex === -1) throw new NotFoundException(`Доповнення не знайдено`);

    const info = request.additionalInfo[infoIndex];

    if (requester.systemRole !== SystemRole.ADMIN) {
      const now = new Date();
      const createdAt = new Date(info.createdAt);
      const diffMs = now.getTime() - createdAt.getTime();
      const diffMins = diffMs / (1000 * 60);

      if (diffMins > 30) {
        throw new ForbiddenException('Редагування можливе лише протягом 30 хвилин після створення');
      }
    }

    const keptAttachments = dto.removedAttachments?.length
      ? (info.attachments || []).filter((a: any) => !dto.removedAttachments!.includes(a.url))
      : info.attachments || [];
    request.additionalInfo[infoIndex] = {
      ...info,
      text: dto.text,
      attachments: dto.attachments?.length ? [...keptAttachments, ...dto.attachments] : keptAttachments,
      updatedAt: new Date(),
    };

    return await this.requestRepository.save(request);
  }

  async removeAdditionalInfo(id: string, infoId: string, requester: User): Promise<Request> {
    const request = await this.requestRepository.findOne({ where: { id } });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== requester.id && requester.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Тільки власник або адміністратор може видаляти доповнення');
    }

    const infoIndex = request.additionalInfo.findIndex((info) => info.id === infoId);
    if (infoIndex === -1) throw new NotFoundException(`Доповнення не знайдено`);

    const info = request.additionalInfo[infoIndex];

    if (requester.systemRole !== SystemRole.ADMIN) {
      const now = new Date();
      const createdAt = new Date(info.createdAt);
      const diffMs = now.getTime() - createdAt.getTime();
      const diffMins = diffMs / (1000 * 60);

      if (diffMins > 30) {
        throw new ForbiddenException('Видалення можливе лише протягом 30 хвилин після створення');
      }
    }

    request.additionalInfo.splice(infoIndex, 1);
    return await this.requestRepository.save(request);
  }

  // ─── Видалення ────────────────────────────────────────────────────────────

  async remove(id: string, requester: User): Promise<void> {
    const request = await this.requestRepository.findOne({
      where: { id },
      relations: ['tasks', 'tasks.assignments'],
    });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== requester.id && requester.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Немає прав для видалення цієї заявки');
    }

    if (requester.systemRole !== SystemRole.ADMIN) {
      const createdAt = request.createdAt?.getTime?.() ?? 0;
      const gracePeriodMs = 10 * 60 * 1000;
      const hasActiveAssignments = request.tasks?.some((task) =>
        task.assignments?.some((a) => isActiveAssignmentStatus(a.status)),
      );

      if (Date.now() - createdAt > gracePeriodMs || hasActiveAssignments) {
        throw new ForbiddenException(
          'Заявку можна видалити лише протягом 10 хвилин після створення і тільки якщо її ще не взяли в роботу. Після цього скасуйте заявку.',
        );
      }
    }

    await this.requestRepository.softDelete(id);
  }

  // ─── Saved Requests ────────────────────────────────────────────────────────
  async saveRequest(requestId: string, userId: string): Promise<void> {
    const exists = await this.savedRequestRepository.findOne({ where: { requestId, userId } });
    if (!exists) {
      const saved = this.savedRequestRepository.create({ requestId, userId });
      await this.savedRequestRepository.save(saved);
    }
  }

  async unsaveRequest(requestId: string, userId: string): Promise<void> {
    await this.savedRequestRepository.delete({ requestId, userId });
  }

  async getSavedRequests(userId: string, limit: number = 50, offset: number = 0): Promise<Request[]> {
    const saved = await this.savedRequestRepository.find({
      where: { userId },
      relations: ['request'],
      take: limit,
      skip: offset,
      order: { savedAt: 'DESC' },
    });
    return saved.map((s) => ({
      ...s.request,
      isSaved: true,
    }));
  }

  async getSavedRequestIds(userId: string): Promise<string[]> {
    const savedRequests = await this.savedRequestRepository.find({
      where: { userId },
      select: ['requestId'],
    });
    return savedRequests.map((r) => r.requestId);
  }

  async getMyRequests(
    creatorId: string,
    options: { limit: number; offset: number },
  ): Promise<any[]> {
    const [requests, total] = await this.requestRepository.findAndCount({
      where: { creatorId },
      order: { createdAt: 'DESC' },
      skip: options.offset,
      take: options.limit,
      relations: ['tasks'],
    });

    return requests.map((r) => {
      return {
        ...r,
        _meta: { total },
      };
    });
  }

  async getRequestsWithPriority(params: {
    userId?: string;
    userLat?: number;
    userLng?: number;
    radiusKm?: number;
    limit?: number;
    offset?: number;
    search?: string;
    status?: string;
    urgency?: string;
    category?: string;
    creatorId?: string;
    excludeCreatorId?: string;
  }): Promise<any[]> {
    const { userId, userLat, userLng, radiusKm, limit = 20, offset = 0, search, status, urgency, category, creatorId, excludeCreatorId } = params;

    // Якщо потрібно сортувати за відстанню - використовуємо raw query,
    // оскільки TypeORM .skip()/.take() дають помилку з об'єднаною aliasing
    if (userLat != null && userLng != null) {
      const sql = `
        SELECT
          req.id AS id,
          req.status,
          req.title,
          req.description,
          req.category,
          req.urgency,
          req.required_clearance AS "requiredClearance",
          req.creator_id AS "creatorId",
          req.managing_organization_id AS "managingOrganizationId",
          req.cancelled_by_user_id AS "cancelledByUserId",
          req.cancelled_at AS "cancelledAt",
          req.cancel_reason AS "cancelReason",
          req.latitude,
          req.longitude,
          req.is_location_hidden AS "isLocationHidden",
          req.tags,
          req.additional_info AS "additionalInfo",
        req.media_urls AS "mediaUrls",
        req."reportUrls" AS "reportUrls",
        req.deadline,
          req.fundraising_url AS "fundraisingUrl",
          req.created_at AS "createdAt",
          req.updated_at AS "updatedAt",
          req.deleted_at AS "deletedAt",
          /* followerIds column not in DB, removed */
          creator.id AS "creator_id",
          creator.full_name AS "creator_fullName",
          creator.email AS "creator_email",
          creator.avatar_url AS "creator_avatarUrl",
          creator.clearance_level AS "creator_clearanceLevel",
          creator.system_role AS "creator_systemRole",
          /* citizenship column not in DB, removed */
          ST_Distance(
            req.exact_location::geography,
            ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography
          ) AS distance
        FROM requests req
        LEFT JOIN users creator ON creator.id = req.creator_id AND creator.deleted_at IS NULL
        WHERE req.deleted_at IS NULL
        ORDER BY distance ASC NULLS LAST
        LIMIT $3 OFFSET $4
      `;
      const results = await this.requestRepository.query(sql, [userLng, userLat, limit, offset]);
      return results.map((r: any) => ({
        id: r.id,
        status: r.status,
        title: r.title,
        description: r.description,
        category: r.category,
        urgency: r.urgency,
        requiredClearance: r.requiredClearance,
        creatorId: r.creatorId,
        managingOrganizationId: r.managingOrganizationId ?? null,
        cancelledByUserId: r.cancelledByUserId ?? null,
        cancelledAt: r.cancelledAt ?? null,
        cancelReason: r.cancelReason ?? null,
        latitude: r.latitude ?? null,
        longitude: r.longitude ?? null,
        isLocationHidden: r.isLocationHidden ?? false,
        tags: typeof r.tags === 'string' ? r.tags.split(',').filter(Boolean) : r.tags ?? [],
        additionalInfo: typeof r.additionalInfo === 'string' ? JSON.parse(r.additionalInfo) : r.additionalInfo ?? [],
        mediaUrls: typeof r.mediaUrls === 'string' ? JSON.parse(r.mediaUrls) : r.mediaUrls ?? [],
        reportUrls: typeof r.reportUrls === 'string' ? r.reportUrls.split(',').filter(Boolean) : r.reportUrls ?? [],
        deadline: r.deadline,
        fundraisingUrl: r.fundraisingUrl ?? null,
        createdAt: r.createdAt,
        updatedAt: r.updatedAt,
        deletedAt: r.deletedAt,
        followerIds: r.followerIds ?? [],
        creator: {
          id: r.creator_id,
          fullName: r.creator_fullName,
          email: r.creator_email,
          avatarUrl: r.creator_avatarUrl,
          clearanceLevel: r.creator_clearanceLevel,
          systemRole: r.creator_systemRole,
          citizenship: r.creator_citizenship,
        },
        distance: r.distance,
      }));
    }

    // Використовуємо raw SQL замість TypeORM query builder через баг з PostGIS geometry
    // колонками: TypeORM падає з "Cannot read properties of undefined (reading 'databaseName')"
    // при використанні .skip()/.take() разом з .leftJoinAndSelect() на таблицях з geometry.
    // Докладно: https://github.com/typeorm/typeorm/issues/...
    const whereClauses: string[] = ['req.deleted_at IS NULL'];
    const rawParams: any[] = [];

    if (status) {
      whereClauses.push(`req.status = $${rawParams.length + 1}`);
      rawParams.push(status);
    }
    if (urgency) {
      whereClauses.push(`req.urgency = $${rawParams.length + 1}`);
      rawParams.push(urgency);
    }
    if (category) {
      whereClauses.push(`req.category = $${rawParams.length + 1}`);
      rawParams.push(category);
    }
    if (creatorId) {
      whereClauses.push(`req.creator_id = $${rawParams.length + 1}`);
      rawParams.push(creatorId);
    }
    if (excludeCreatorId) {
      whereClauses.push(`req.creator_id != $${rawParams.length + 1}`);
      rawParams.push(excludeCreatorId);
    }
    if (search) {
      whereClauses.push(
        `(req.title ILIKE $${rawParams.length + 1} OR req.description ILIKE $${rawParams.length + 2})`,
      );
      rawParams.push(`%${search}%`, `%${search}%`);
    }

    const whereSQL = whereClauses.join(' AND ');

    const sql = `
      SELECT
        req.id AS id,
        req.status,
        req.title,
        req.description,
        req.category,
        req.urgency,
        req.required_clearance AS "requiredClearance",
        req.creator_id AS "creatorId",
        req.managing_organization_id AS "managingOrganizationId",
        req.cancelled_by_user_id AS "cancelledByUserId",
        req.cancelled_at AS "cancelledAt",
        req.cancel_reason AS "cancelReason",
        req.latitude,
        req.longitude,
        req.is_location_hidden AS "isLocationHidden",
        req.tags,
        req.additional_info AS "additionalInfo",
        req.media_urls AS "mediaUrls",
        req."reportUrls" AS "reportUrls",
        req.deadline,
        req.fundraising_url AS "fundraisingUrl",
        req.created_at AS "createdAt",
        req.updated_at AS "updatedAt",
        req.deleted_at AS "deletedAt",
        /* followerIds column not in DB, removed */
        creator.id AS "creator_id",
        creator.full_name AS "creator_fullName",
        creator.email AS "creator_email",
        creator.avatar_url AS "creator_avatarUrl",
        creator.clearance_level AS "creator_clearanceLevel",
        creator.system_role AS "creator_systemRole"
      FROM requests req
      LEFT JOIN users creator ON creator.id = req.creator_id AND creator.deleted_at IS NULL
      WHERE ${whereSQL}
      ORDER BY req.created_at DESC
      LIMIT $${rawParams.length + 1} OFFSET $${rawParams.length + 2}
    `;
    rawParams.push(limit, offset);

    try {
      const results = await this.requestRepository.query(sql, rawParams);
      return results.map((r: any) => ({
        id: r.id,
        status: r.status,
        title: r.title,
        description: r.description,
        category: r.category,
        urgency: r.urgency,
        requiredClearance: r.requiredClearance,
        creatorId: r.creatorId,
        managingOrganizationId: r.managingOrganizationId ?? null,
        cancelledByUserId: r.cancelledByUserId ?? null,
        cancelledAt: r.cancelledAt ?? null,
        cancelReason: r.cancelReason ?? null,
        latitude: r.latitude ?? null,
        longitude: r.longitude ?? null,
        isLocationHidden: r.isLocationHidden ?? false,
        tags: typeof r.tags === 'string' ? r.tags.split(',').filter(Boolean) : r.tags ?? [],
        additionalInfo: typeof r.additionalInfo === 'string' ? JSON.parse(r.additionalInfo) : r.additionalInfo ?? [],
        mediaUrls: typeof r.mediaUrls === 'string' ? JSON.parse(r.mediaUrls) : r.mediaUrls ?? [],
        reportUrls: typeof r.reportUrls === 'string' ? r.reportUrls.split(',').filter(Boolean) : r.reportUrls ?? [],
        deadline: r.deadline,
        fundraisingUrl: r.fundraisingUrl ?? null,
        createdAt: r.createdAt,
        updatedAt: r.updatedAt,
        deletedAt: r.deletedAt,
        followerIds: r.followerIds ?? [],
        creator: {
          id: r.creator_id,
          fullName: r.creator_fullName,
          email: r.creator_email,
          avatarUrl: r.creator_avatarUrl,
          clearanceLevel: r.creator_clearanceLevel,
          systemRole: r.creator_systemRole,
          citizenship: r.creator_citizenship,
        },
      }));
    } catch (err) {
      console.error('[DEBUG getRequestsWithPriority] SQL error:', err);
      console.error('[DEBUG getRequestsWithPriority] sql:', sql);
      console.error('[DEBUG getRequestsWithPriority] params:', rawParams);
      throw err;
    }
  }

  // ─── Статусні операції ─────────────────────────────────────────────────

  async markAsPendingReview(id: string, user: User): Promise<Request> {
    const request = await this.requestRepository.findOne({ where: { id } });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== user.id && user.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Тільки власник або адмін може змінити статус');
    }

    request.status = RequestStatus.PENDING_REVIEW;
    return this.requestRepository.save(request);
  }

  async cancel(id: string, reason: string | undefined, user: User): Promise<Request> {
    const request = await this.requestRepository.findOne({ where: { id } });
    if (!request) throw new NotFoundException(`Р—Р°СЏРІРєСѓ ${id} РЅРµ Р·РЅР°Р№РґРµРЅРѕ`);

    const isOwner = request.creatorId === user.id;
    const isAdmin = user.systemRole === SystemRole.ADMIN;
    const isCoordinator = user.systemRole === SystemRole.COORDINATOR;
    if (!isOwner && !isAdmin && !isCoordinator) {
      throw new ForbiddenException('РќРµРјР°С” РїСЂР°РІ РґР»СЏ СЃРєР°СЃСѓРІР°РЅРЅСЏ С†С–С”С— Р·Р°СЏРІРєРё');
    }

    if (request.status === RequestStatus.COMPLETED) {
      throw new ForbiddenException('Р—Р°РІРµСЂС€РµРЅСѓ Р·Р°СЏРІРєСѓ РЅРµ РјРѕР¶РЅР° СЃРєР°СЃСѓРІР°С‚Рё');
    }

    request.status = RequestStatus.CANCELLED;
    request.cancelReason = reason?.trim() || null;
    request.cancelledAt = new Date();
    request.cancelledByUserId = user.id;
    return this.requestRepository.save(request);
  }

  async confirmCompletion(id: string, user: User): Promise<Request> {
    const request = await this.requestRepository.findOne({ where: { id } });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== user.id && user.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Тільки власник або адмін може підтвердити виконання');
    }

    request.status = RequestStatus.COMPLETED;
    return this.requestRepository.save(request);
  }

  async returnToProgress(id: string, user: User): Promise<Request> {
    const request = await this.requestRepository.findOne({ where: { id } });
    if (!request) throw new NotFoundException(`Заявку ${id} не знайдено`);

    if (request.creatorId !== user.id && user.systemRole !== SystemRole.ADMIN) {
      throw new ForbiddenException('Тільки власник або адмін може повернути в роботу');
    }

    // Якщо заявка скасована — дозволити повернути лише протягом 10 хвилин
    if (request.status === RequestStatus.CANCELLED) {
      const cancelledAt = request.cancelledAt;
      if (!cancelledAt) {
        throw new ForbiddenException('Неможливо визначити час скасування заявки');
      }

      const now = Date.now();
      const cancelledTime = cancelledAt.getTime();
      const diffMs = now - cancelledTime;
      const tenMinutes = 10 * 60 * 1000;

      if (diffMs > tenMinutes) {
        throw new ForbiddenException('Час для відміни скасування вичерпано. Можливо повернути лише протягом 10 хвилин після скасування.');
      }

      // Очищуємо дані скасування і повертаємо в активний статус
      request.status = RequestStatus.IN_PROGRESS;
      request.cancelReason = null;
      request.cancelledAt = null;
      request.cancelledByUserId = null;

      return this.requestRepository.save(request);
    }

    // Для інших статусів (напр. PENDING_REVIEW) — стандартна логіка
    request.status = RequestStatus.IN_PROGRESS;
    return this.requestRepository.save(request);
  }

  // ─── Приватні методи ────────────────────────────────────────────────────

  private autoCategorizeTags(text: string): string[] {
    const lower = text.toLowerCase();
    const tags: string[] = [];

    for (const [tag, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
      if (keywords.some((kw) => lower.includes(kw))) {
        tags.push(tag);
      }
    }

    return tags;
  }

  private getClearanceRank(level: ClearanceLevel): number {
    switch (level) {
      case ClearanceLevel.LOCAL:        return 0;
      case ClearanceLevel.INTERNATIONAL: return 1;
      case ClearanceLevel.FRONTLINE:    return 2;
      default:                          return 0;
    }
  }

  private obfuscateLocation(request: Request, viewer: User): Request {
    const isOwner = viewer.id === request.creatorId;
    const isCoordinator = viewer.systemRole === SystemRole.COORDINATOR;
    const isAdmin = viewer.systemRole === SystemRole.ADMIN;
    const isFrontline = viewer.clearanceLevel === ClearanceLevel.FRONTLINE;

    // Власник, координатор та адмін бачать точні координати
    if (isOwner || isCoordinator || isAdmin || isFrontline) {
      return request; // без обфускації
    }

    if (!request.latitude || !request.longitude) return request;

    // Додаємо випадкове зміщення в межах OBFUSCATION_RADIUS_M
    const angle = Math.random() * 2 * Math.PI;
    const offsetMeters = Math.random() * OBFUSCATION_RADIUS_M;
    const earthRadius = 6371000;

    const latOffset = (offsetMeters / earthRadius) * (180 / Math.PI);
    const lngOffset =
      (offsetMeters / earthRadius) * (180 / Math.PI) / Math.cos((request.latitude * Math.PI) / 180);

    return {
      ...request,
      latitude: request.latitude + Math.cos(angle) * latOffset,
      longitude: request.longitude + Math.sin(angle) * lngOffset,
    };
  }

  private checkClearanceAccess(request: Request, user: User): void {
    const clearanceRank = this.getClearanceRank(user.clearanceLevel);
    const requiredRank = this.getClearanceRank(
      (request as any).requiredClearance || ClearanceLevel.LOCAL,
    );

    if (
      user.systemRole !== SystemRole.ADMIN &&
      user.systemRole !== SystemRole.COORDINATOR &&
      clearanceRank < requiredRank
    ) {
      throw new ForbiddenException('Недостатній рівень допуску для перегляду цієї заявки');
    }
  }

  private async logAccess(
    request: Request,
    user: User,
    action: AccessAction,
  ): Promise<void> {
    // Логуємо тільки FRONTLINE заявки, і тільки коли користувач не є власником
    const requiredClearance = (request as any).requiredClearance;
    if (requiredClearance !== ClearanceLevel.FRONTLINE) return;
    if (request.creatorId === user.id) return;

    try {
      await this.accessLogRepository.save({
        userId: user.id,
        requestId: request.id,
        action,
        clearanceAtAccess: user.clearanceLevel,
      });
    } catch (err) {
      // Логування не повинно блокувати основний запит
      console.error('[AccessLog] Failed to log access:', err);
    }
  }

  // ─── Admin: access logs with filters ─────────────────────────────────────────
  async getAccessLogs(filters: {
    requestId?: string;
    userId?: string;
    action?: string;
    from?: string;
    to?: string;
    limit: number;
    offset: number;
  }): Promise<any[]> {
    const qb = this.accessLogRepository
      .createQueryBuilder('al')
      .leftJoinAndSelect('al.request', 'request')
      .orderBy('al.createdAt', 'DESC')
      .take(filters.limit)
      .skip(filters.offset);

    if (filters.requestId) {
      qb.andWhere('al.requestId = :requestId', { requestId: filters.requestId });
    }
    if (filters.userId) {
      qb.andWhere('al.userId = :userId', { userId: filters.userId });
    }
    if (filters.action) {
      qb.andWhere('al.action = :action', { action: filters.action });
    }
    if (filters.from) {
      qb.andWhere('al.createdAt >= :from', { from: new Date(filters.from) });
    }
    if (filters.to) {
      qb.andWhere('al.createdAt <= :to', { to: new Date(filters.to) });
    }

    const logs = await qb.getMany();
    return logs.map((log) => ({
      id: log.id,
      userId: log.userId,
      requestId: log.requestId,
      action: log.action,
      ip: log.ip,
      userAgent: log.userAgent,
      clearanceAtAccess: log.clearanceAtAccess,
      requestTitle: (log as any).request?.title || null,
      createdAt: log.createdAt,
    }));
  }
}
